-- Execute este arquivo UMA vez no SQL Editor do Supabase.
-- Cria metas pessoais e metas de contas conjuntas.

create table if not exists public.metas (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  conta_id uuid references public.contas(id) on delete set null,
  titulo text not null check (char_length(trim(titulo)) >= 2),
  valor_meta numeric(12,2) not null check (valor_meta > 0),
  valor_atual numeric(12,2) not null default 0 check (valor_atual >= 0),
  moeda text not null default 'EUR' check (moeda in ('BRL', 'EUR')),
  prazo date,
  created_at timestamptz not null default now()
);

create index if not exists metas_user_conta_idx on public.metas (user_id, conta_id, created_at desc);

alter table public.metas enable row level security;

drop policy if exists metas_select on public.metas;
drop policy if exists metas_insert on public.metas;
drop policy if exists metas_update on public.metas;
drop policy if exists metas_delete on public.metas;

create policy metas_select on public.metas for select to authenticated
  using (
    (conta_id is null and user_id = auth.uid())
    or (conta_id is not null and public.eh_membro_conta(conta_id))
  );

create policy metas_insert on public.metas for insert to authenticated
  with check (
    user_id = auth.uid()
    and (conta_id is null or public.eh_membro_conta(conta_id))
  );

create policy metas_update on public.metas for update to authenticated
  using (
    (conta_id is null and user_id = auth.uid())
    or (conta_id is not null and public.eh_membro_conta(conta_id))
  )
  with check (
    (conta_id is null and user_id = auth.uid())
    or (conta_id is not null and public.eh_membro_conta(conta_id))
  );

create policy metas_delete on public.metas for delete to authenticated
  using (
    (conta_id is null and user_id = auth.uid())
    or (conta_id is not null and public.eh_membro_conta(conta_id))
  );
