-- Execute este arquivo UMA vez no SQL Editor do Supabase.
-- Cria contas conjuntas, códigos de convite e o histórico de alterações.

create table if not exists public.contas (
  id uuid primary key default gen_random_uuid(),
  nome text not null check (char_length(trim(nome)) >= 2),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  codigo_convite text not null unique check (codigo_convite ~ '^[A-Z0-9]{4}-[A-Z0-9]{4}$'),
  created_at timestamptz not null default now()
);

create table if not exists public.conta_membros (
  conta_id uuid not null references public.contas(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  papel text not null default 'membro' check (papel in ('proprietario', 'membro')),
  joined_at timestamptz not null default now(),
  primary key (conta_id, user_id)
);

create or replace function public.eh_membro_conta(p_conta_id uuid)
returns boolean language sql security definer set search_path = public stable as $$
  select exists (select 1 from public.conta_membros where conta_id = p_conta_id and user_id = auth.uid());
$$;

create or replace function public.adicionar_dono_da_conta()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.conta_membros (conta_id, user_id, papel) values (new.id, new.owner_id, 'proprietario');
  return new;
end;
$$;

drop trigger if exists conta_adiciona_dono on public.contas;
create trigger conta_adiciona_dono after insert on public.contas
  for each row execute function public.adicionar_dono_da_conta();

create or replace function public.entrar_conta_compartilhada(p_codigo text)
returns uuid language plpgsql security definer set search_path = public as $$
declare v_conta_id uuid;
begin
  select id into v_conta_id from public.contas where codigo_convite = upper(trim(p_codigo));
  if v_conta_id is null then raise exception 'Código de convite não encontrado.'; end if;
  insert into public.conta_membros (conta_id, user_id, papel)
    values (v_conta_id, auth.uid(), 'membro') on conflict (conta_id, user_id) do nothing;
  return v_conta_id;
end;
$$;

alter table public.contas enable row level security;
alter table public.conta_membros enable row level security;

drop policy if exists contas_select on public.contas;
drop policy if exists contas_insert on public.contas;
drop policy if exists contas_update on public.contas;
drop policy if exists contas_delete on public.contas;
drop policy if exists membros_select on public.conta_membros;

create policy contas_select on public.contas for select to authenticated
  using (owner_id = auth.uid() or public.eh_membro_conta(id));
create policy contas_insert on public.contas for insert to authenticated
  with check (owner_id = auth.uid());
create policy contas_update on public.contas for update to authenticated
  using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy contas_delete on public.contas for delete to authenticated
  using (owner_id = auth.uid());
create policy membros_select on public.conta_membros for select to authenticated
  using (public.eh_membro_conta(conta_id));

grant execute on function public.entrar_conta_compartilhada(text) to authenticated;

alter table public.lancamentos add column if not exists conta_id uuid references public.contas(id) on delete set null;
alter table public.lancamentos add column if not exists created_by uuid references public.profiles(id) on delete set null;
alter table public.lancamentos add column if not exists updated_by uuid references public.profiles(id) on delete set null;
update public.lancamentos set created_by = user_id, updated_by = user_id where created_by is null or updated_by is null;

create or replace function public.definir_autores_lancamento()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if tg_op = 'INSERT' then new.created_by := auth.uid(); end if;
  new.updated_by := auth.uid();
  return new;
end;
$$;

drop trigger if exists lancamentos_definem_autores on public.lancamentos;
create trigger lancamentos_definem_autores before insert or update on public.lancamentos
  for each row execute function public.definir_autores_lancamento();

create table if not exists public.lancamento_historico (
  id bigint generated by default as identity primary key,
  lancamento_id bigint not null,
  conta_id uuid references public.contas(id) on delete set null,
  acao text not null check (acao in ('criou', 'editou', 'excluiu')),
  autor_id uuid references public.profiles(id) on delete set null,
  autor_nome text,
  detalhes jsonb,
  ocorrido_em timestamptz not null default now()
);

create index if not exists lancamento_historico_conta_data_idx on public.lancamento_historico (conta_id, ocorrido_em desc);

create or replace function public.registrar_historico_lancamento()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_autor_id uuid := auth.uid(); v_autor_nome text;
begin
  select nome into v_autor_nome from public.profiles where id = v_autor_id;
  if tg_op = 'INSERT' then
    insert into public.lancamento_historico (lancamento_id, conta_id, acao, autor_id, autor_nome, detalhes)
      values (new.id, new.conta_id, 'criou', v_autor_id, v_autor_nome, to_jsonb(new));
    return new;
  elsif tg_op = 'UPDATE' then
    insert into public.lancamento_historico (lancamento_id, conta_id, acao, autor_id, autor_nome, detalhes)
      values (new.id, new.conta_id, 'editou', v_autor_id, v_autor_nome, to_jsonb(new));
    return new;
  else
    insert into public.lancamento_historico (lancamento_id, conta_id, acao, autor_id, autor_nome, detalhes)
      values (old.id, old.conta_id, 'excluiu', v_autor_id, v_autor_nome, to_jsonb(old));
    return old;
  end if;
end;
$$;

drop trigger if exists lancamentos_registram_historico on public.lancamentos;
create trigger lancamentos_registram_historico after insert or update or delete on public.lancamentos
  for each row execute function public.registrar_historico_lancamento();

alter table public.lancamento_historico enable row level security;
drop policy if exists historico_select on public.lancamento_historico;
create policy historico_select on public.lancamento_historico for select to authenticated
  using (autor_id = auth.uid() or (conta_id is not null and public.eh_membro_conta(conta_id)));

drop policy if exists "Lancamentos do proprio utilizador" on public.lancamentos;
drop policy if exists lancamentos_select on public.lancamentos;
drop policy if exists lancamentos_insert on public.lancamentos;
drop policy if exists lancamentos_update on public.lancamentos;
drop policy if exists lancamentos_delete on public.lancamentos;

create policy lancamentos_select on public.lancamentos for select to authenticated
  using ((conta_id is null and user_id = auth.uid()) or (conta_id is not null and public.eh_membro_conta(conta_id)));
create policy lancamentos_insert on public.lancamentos for insert to authenticated
  with check (user_id = auth.uid() and (conta_id is null or public.eh_membro_conta(conta_id)));
create policy lancamentos_update on public.lancamentos for update to authenticated
  using ((conta_id is null and user_id = auth.uid()) or (conta_id is not null and public.eh_membro_conta(conta_id)))
  with check ((conta_id is null and user_id = auth.uid()) or (conta_id is not null and public.eh_membro_conta(conta_id)));
create policy lancamentos_delete on public.lancamentos for delete to authenticated
  using ((conta_id is null and user_id = auth.uid()) or (conta_id is not null and public.eh_membro_conta(conta_id)));
