-- Execute este arquivo UMA vez no SQL Editor do Supabase.
-- Salva categorias criadas manualmente para a conta pessoal ou conjunta.

create table if not exists public.categorias (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  conta_id uuid references public.contas(id) on delete cascade,
  nome text not null check (char_length(trim(nome)) between 2 and 60),
  created_at timestamptz not null default now()
);

create unique index if not exists categorias_pessoais_unicas
  on public.categorias (user_id, lower(nome)) where conta_id is null;

create unique index if not exists categorias_conjuntas_unicas
  on public.categorias (conta_id, lower(nome)) where conta_id is not null;

create index if not exists categorias_por_conta_idx
  on public.categorias (conta_id, nome);

alter table public.categorias enable row level security;

drop policy if exists categorias_select on public.categorias;
drop policy if exists categorias_insert on public.categorias;
drop policy if exists categorias_update on public.categorias;
drop policy if exists categorias_delete on public.categorias;

create policy categorias_select on public.categorias for select to authenticated
  using (
    (conta_id is null and user_id = auth.uid())
    or (conta_id is not null and public.eh_membro_conta(conta_id))
  );

create policy categorias_insert on public.categorias for insert to authenticated
  with check (
    user_id = auth.uid()
    and (conta_id is null or public.eh_membro_conta(conta_id))
  );

create policy categorias_update on public.categorias for update to authenticated
  using (
    (conta_id is null and user_id = auth.uid())
    or (conta_id is not null and public.eh_membro_conta(conta_id))
  )
  with check (
    (conta_id is null and user_id = auth.uid())
    or (conta_id is not null and public.eh_membro_conta(conta_id))
  );

create policy categorias_delete on public.categorias for delete to authenticated
  using (
    (conta_id is null and user_id = auth.uid())
    or (conta_id is not null and public.eh_membro_conta(conta_id))
  );
