-- Execute este ficheiro no SQL Editor do Supabase antes de utilizar a aplicação.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.lancamentos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  data date not null,
  tipo text not null check (tipo in ('Recebimento', 'Gasto')),
  categoria text not null,
  descricao text not null,
  valor numeric(12,2) not null check (valor > 0),
  moeda text not null default 'BRL' check (moeda in ('BRL', 'EUR')),
  created_at timestamptz not null default now()
);

create index if not exists lancamentos_user_data_idx on public.lancamentos (user_id, data desc);

alter table public.profiles enable row level security;
alter table public.lancamentos enable row level security;

create policy "Perfil do proprio utilizador" on public.profiles
  for all to authenticated using (auth.uid() = id) with check (auth.uid() = id);

create policy "Lancamentos do proprio utilizador" on public.lancamentos
  for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
